"""add queued job status

Revision ID: c83445995db0
Revises: d6bc6bcd0d7a
Create Date: 2026-10-02 19:32:56.600565

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c83445995db0'
down_revision: Union[str, Sequence[str], None] = 'd6bc6bcd0d7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    op.execute(
        "ALTER TYPE jobstatus ADD VALUE IF NOT EXISTS 'QUEUED'"
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
