"""add next retry time

Revision ID: d6bc6bcd0d7a
Revises: 69e019265ab6
Create Date: 2026-10-02 18:08:52.599665

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6bc6bcd0d7a'
down_revision: Union[str, Sequence[str], None] = '69e019265ab6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('next_retry_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'next_retry_at')
    # ### end Alembic commands ###
